### ISSUE TITLE
react-native-svg should be listed as a dependency

### ISSUE THREAD

**Issue by corymsmith** [nating/react-native-custom-qr-codes#4]
The install instructions don't mention it at all.

**Comment by nabilalilipaly08** [comment]
So how to solve this? just install react-native-svg?

**Comment by corymsmith** [comment]
Yes

**Comment by nating** [comment]
Pull request [is here](https://github.com/nating/react-native-custom-qr-codes/pull/7)- don't have time to test it out right now.

**Comment by mnorkin** [comment]
Please close the issue
