### ISSUE TITLE
Way to export QR code

### ISSUE THREAD

**Issue by MeKyleH** [nating/react-native-custom-qr-codes#9]
Is there a way to export the QR Code once we generate it? I haven't been able to find a src property or something similar that I could convert to base64 or a blob or anything for exporting or saving to a database. Is there a way to save the QR code as an image?

**Comment by nating** [comment]
Hey @MeKyleH! There is a way, though it might be a bit out of scope. The QR codes use react-native-svg, and it seems that you can save those SVG components to the gallery. The implementation of this was discussed in an issue [here](https://github.com/awesomejerry/react-native-qrcode-svg/issues/13) on [this other](https://github.com/awesomejerry/react-native-qrcode-svg) React Native QR code library. The person who wanted to save the QR code had success with [this code](https://github.com/awesomejerry/react-native-qrcode-svg/pull/14/files), but that library has a toDataUrl function for converting the SVG to base64 so there might need to be a PR for that here.
